# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64ef5c7bb52e6c123b77f56029207962be34c8e631c53f6572708c6e3b02c164d6c5b78f1ef8f78bab9e1b0b38136a243b1037ac9a54f6091407ec29d3c2624f

test:
  secret_key_base: 593ee66d972a848a393e7f9b55f0560b3cdbfc37cb3c81f095a4ed65b61368c576650116c508fe28a3df6b788efbdab6f1f5d0c89c1ca2063b442b497873b8fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
